language: android
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - extra-android-m2repository
  - android-24
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_19f97a59b04f_key -iv $encrypted_19f97a59b04f_iv
  -in leo.jks.enc -out keys/leo.jks -d
- gem install fir-cli
script:
- ./gradlew assembleRelease
after_success:
- fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
